Code cosmetics.

diff --git a/templates/create_slot.sh.erb b/templates/create_slot.sh.erb
--- a/templates/create_slot.sh.erb
+++ b/templates/create_slot.sh.erb
@@ -1,17 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 # By Fat Dragon, 05/24/2016
 # (Re)creates replication slot.
 # NOTE: The script should be executed as postgres user
 
 echo "create_slot - Start"
-
-# Ensuring that 'postgres' runs the script
-if [ "$(id -u)" -ne "$(id -u postgres)" ]; then
-
-        echo "ERROR: The script must be executed as 'postgres' user."
-        exit 1
-
-fi
 
 # Defining default values
 trigger_file="<%= @config_dir_used %>/im_the_master"
@@ -21,101 +13,153 @@ recreate=false
 debug=true
 
 while test $# -gt 0; do
-        case "$1" in
-                -h|--help)
-                        echo "Creates replication slot"
-                        echo " "
-                        echo "create_slot [options]"
-                        echo " "
-                        echo "options:"
-                        echo "-h, --help                show brief help"
-                        echo "-t, --trigger_file=FILE   specify trigger file path"
-						echo "    Optional, default: <%= @config_dir_used %>/im_the_master"
-                        echo "-n, --name=NAME           slot name (mandatory)"
-						echo "                          Slot name can be also specified without using"
-						echo "                          flags (i.e. 'create_slot myslot')"
-						echo "-r, --recreate            Forces re-creation if the slot already exists"
-						echo "    Optional, default: N/A"
-						echo "    Description:       Without this flag the script won't do anything if"
-						echo "                       the slot with defined name already exists."
-						echo "                       With the flag set, if the slot with defined name"
-						echo "                       already exists it will be deleted and re-created."
-						echo " "
-						echo "Error Codes:"
-						echo "  1 - Wrong user. The script has to be executed as 'postgres' user."
-						echo "  2 - Argument error. Caused either by bad format of provided flags and"
-						echo "      arguments or if a mandatory argument is missing."
-						echo "  3 - Inapropriate trigger / standby files. This script REQUIRES trigger"
-						echo "      file to be present."
-						echo "  4 - Error executing a slot-related operation (query/create/drop)."
-                        exit 0
-                        ;;
-				-t)
-						shift
-                        if test $# -gt 0; then
-                                trigger_file=$1
-                        else
-                                echo "ERROR: -t flag requires trigger file to be specified."
-                                exit 2
-                        fi
-                        shift
-                        ;;
-                --trigger-file=*)
-                        trigger_file=`echo $1 | sed -e 's/^[^=]*=//g'`
-                        shift
-                        ;;
-				-n)
-						if [ "$slot_name" != "" ]; then
-							echo "ERROR: Invalid command. For help execute 'create_slot -h'"
-							exit 2
-						fi
-						
-						shift
-                        if test $# -gt 0; then
-                                slot_name=$1
-                        else
-                                echo "ERROR: -n flag requires slot name to be specified."
-                                exit 2
-                        fi
-                        shift
-                        ;;
-                --name=*)
-						if [ "$slot_name" != "" ]; then
-							echo "ERROR: Invalid command. For help execute 'create_slot -h'"
-							exit 2
-						fi
-						
-                        slot_name=`echo $1 | sed -e 's/^[^=]*=//g'`
-                        shift
-                        ;;
-                -r|--recreate)
-                        recreate=true
-                        shift
-                        ;;
-                *)
-						if [ "$slot_name" != "" ]; then
-							echo "ERROR: Invalid command. For help execute 'create_slot -h'"
-							exit 2
-						fi
-						
-						slot_name=$1
-						shift
-                        ;;
-        esac
+
+    case "$1" in
+
+        -h|--help)
+
+            echo "Creates replication slot"
+            echo " "
+            echo "create_slot [options]"
+            echo " "
+            echo "options:"
+            echo "-h, --help                show brief help"
+            echo "-t, --trigger_file=FILE   specify trigger file path"
+			echo "    Optional, default: <%= @config_dir_used %>/im_the_master"
+            echo "-n, --name=NAME           slot name (mandatory)"
+			echo "                          Slot name can be also specified without using"
+			echo "                          flags (i.e. 'create_slot myslot')"
+			echo "-r, --recreate            Forces re-creation if the slot already exists"
+			echo "    Optional, default: N/A"
+			echo "    Description:       Without this flag the script won't do anything if"
+			echo "                       the slot with defined name already exists."
+			echo "                       With the flag set, if the slot with defined name"
+			echo "                       already exists it will be deleted and re-created."
+			echo " "
+			echo "Error Codes:"
+			echo "  1 - Wrong user. The script has to be executed as 'postgres' user."
+			echo "  2 - Argument error. Caused either by bad format of provided flags and"
+			echo "      arguments or if a mandatory argument is missing."
+			echo "  3 - Inapropriate trigger / standby files. This script REQUIRES trigger"
+			echo "      file to be present."
+			echo "  4 - Error executing a slot-related operation (query/create/drop)."
+            exit 0
+            ;;
+
+		-t)
+			
+			shift
+            
+            if test $# -gt 0; then
+            
+                trigger_file=$1
+            
+            else
+            
+                echo "ERROR: -t flag requires trigger file to be specified."
+                exit 2
+            
+            fi
+            
+            shift
+            ;;
+        
+        --trigger-file=*)
+        
+            trigger_file=`echo $1 | sed -e 's/^[^=]*=//g'`
+        
+            shift
+            ;;
+		
+		-n)
+		
+			if [ "$slot_name" != "" ]; then
+		
+				echo "ERROR: Invalid command. For help execute 'create_slot -h'"
+				exit 2
+		
+			fi
+			
+			shift
+        
+            if test $# -gt 0; then
+        
+                slot_name=$1
+            
+            else
+            
+                echo "ERROR: -n flag requires slot name to be specified."
+                exit 2
+            
+            fi
+            
+            shift
+            ;;
+
+        --name=*)
+		    
+		    if [ "$slot_name" != "" ]; then
+			
+				echo "ERROR: Invalid command. For help execute 'create_slot -h'"
+				exit 2
+			
+			fi
+			
+            slot_name=`echo $1 | sed -e 's/^[^=]*=//g'`
+            
+            shift
+            ;;
+
+        -r|--recreate)
+
+            recreate=true
+
+            shift
+            ;;
+
+        *)
+
+			if [ "$slot_name" != "" ]; then
+				
+				echo "ERROR: Invalid command. For help execute 'create_slot -h'"
+				exit 2
+			
+			fi
+			
+			slot_name=$1
+			
+			shift
+            ;;
+
+    esac
+
 done
 
+# Ensuring that 'postgres' runs the script
+if [ "$(id -u)" -ne "$(id -u postgres)" ]; then
+
+    echo "ERROR: The script must be executed as 'postgres' user."
+    exit 1
+
+fi
+
 if [ "$slot_name" = "" ]; then
+
 	echo "ERROR: Slot name is mandatory. For help execute 'create_slot -h'"
 	exit 2
+
 fi
 
 if $debug; then
+
 	echo "DEBUG: The script will be executed with the following arguments:"
 	echo "DEBUG: --trigger-file=${trigger_file}"
 	echo "DEBUG: --name=${slot_name}"
+	
 	if $recreate; then
 		echo "DEBUG: --recreate"
 	fi
+    
 fi
 
 echo "Checking if trigger file exists..."
diff --git a/templates/promote.sh.erb b/templates/promote.sh.erb
--- a/templates/promote.sh.erb
+++ b/templates/promote.sh.erb
@@ -1,17 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 # By Fat Dragon, 05/24/2016
 # Promoting standby to primary node
 # NOTE: The script should be executed as postgres user
 
 echo "promote - Start"
-
-# Ensuring that 'postgres' runs the script
-if [ "$(id -u)" -ne "$(id -u postgres)" ]; then
-
-        echo "ERROR: The script must be executed as 'postgres' user."
-        exit 1
-
-fi
 
 # Defining default values
 trigger_file="<%= @config_dir_used %>/im_the_master"
@@ -24,149 +16,225 @@ force=false
 debug=true
 
 while test $# -gt 0; do
-        case "$1" in
-                -h|--help)
-                        echo "Promotes a standby server to primary role"
-                        echo " "
-                        echo "promote [options]"
-                        echo " "
-                        echo "options:"
-                        echo "-h, --help                show brief help"
-                        echo "-t, --trigger_file=FILE   specify trigger file path"
-						echo "    Optional, default: <%= @config_dir_used %>/im_the_master"
-                        echo "-s, --standby_file=FILE   specify standby file path"
-						echo "    Optional, default: <%= @config_dir_used %>/im_slave"
-                        echo "-d, --demote=HOST         specify old primary to demote"
-						echo "    Optional, if not specified no demotion will be performed."
-						echo "-u, --user                specify replication role"
-						echo "    Optional, default: replication"
-						echo "-p, --password=PASSWORD   specify password for --user (mandatory)"
-						echo "-f, --force               Forces promotion regardless of existence"
-						echo "                          of trigger / standby files."
-						echo "    Optional, default: N/A"
-						echo "    Description:       Without this flag the script will require"
-						echo "                       presence of trigger file."
-						echo "                       With the flag set the script will create"
-						echo "                       trigger file as needed."
-						echo " "
-						echo "Error Codes:"
-						echo "  1 - Wrong user. The script has to be executed as 'postgres' user."
-						echo "  2 - Argument error. Caused either by bad format of provided flags and"
-						echo "      arguments or if a mandatory argument is missing."
-						echo "  3 - Inapropriate trigger / standby files. See -f flag for details."
-						echo "  4 - Error creating/deleting/copying configuration files"
-						echo "      (postgresql.conf and recovery.conf)."
-						echo "      Hint: ensure that templates exist and check permissions."
-						echo "  5 - Error creating / altering replication_user."
-                        exit 0
-                        ;;
-				-t)
-						shift
-                        if test $# -gt 0; then
-                                trigger_file=$1
-                        else
-                                echo "ERROR: -t flag requires trigger file to be specified."
-                                exit 2
-                        fi
-                        shift
-                        ;;
-                --trigger-file=*)
-                        trigger_file=`echo $1 | sed -e 's/^[^=]*=//g'`
-                        shift
-                        ;;
-				-s)
-						shift
-                        if test $# -gt 0; then
-                                standby_file=$1
-                        else
-                                echo "ERROR: -s flag requires standby file to be specified."
-                                exit 2
-                        fi
-                        shift
-                        ;;
-                --standby-file=*)
-                        standby_file=`echo $1 | sed -e 's/^[^=]*=//g'`
-                        shift
-                        ;;
-				-d)
-						shift
-                        if test $# -gt 0; then
-                                demote_host=$1
-                        else
-                                echo "ERROR: -d flag requires host that will be demoted to be specified."
-                                exit 2
-                        fi
-                        shift
-                        ;;
-                --demote-host=*)
-                        demote_host=`echo $1 | sed -e 's/^[^=]*=//g'`
-                        shift
-                        ;;
-				-u)
-						shift
-                        if test $# -gt 0; then
-                                replication_user=$1
-                        else
-                                echo "ERROR: -u flag requires replication user to be specified."
-                                exit 2
-                        fi
-                        shift
-                        ;;
-                --user=*)
-                        replication_user=`echo $1 | sed -e 's/^[^=]*=//g'`
-                        shift
-                        ;;
-				-p)
-						shift
-                        if test $# -gt 0; then
-                                replication_password=$1
-                        else
-                                echo "ERROR: -p flag requires replication password to be specified."
-                                exit 2
-                        fi
-                        shift
-                        ;;
-                --password=*)
-                        replication_password=`echo $1 | sed -e 's/^[^=]*=//g'`
-                        shift
-                        ;;
-                -f|--force)
-                        force=true
-                        shift
-                        ;;
-                *)
-						echo "ERROR: Unrecognized option $1"
-						exit 2
-                        ;;
-        esac
+
+    case "$1" in
+    
+        -h|--help)
+    
+            echo "Promotes a standby server to primary role"
+            echo " "
+            echo "promote [options]"
+            echo " "
+            echo "options:"
+            echo "-h, --help                show brief help"
+            echo "-t, --trigger_file=FILE   specify trigger file path"
+			echo "    Optional, default: <%= @config_dir_used %>/im_the_master"
+            echo "-s, --standby_file=FILE   specify standby file path"
+			echo "    Optional, default: <%= @config_dir_used %>/im_slave"
+            echo "-d, --demote=HOST         specify old primary to demote"
+			echo "    Optional, if not specified no demotion will be performed."
+			echo "-u, --user                specify replication role"
+			echo "    Optional, default: replication"
+			echo "-p, --password=PASSWORD   specify password for --user (mandatory)"
+			echo "-f, --force               Forces promotion regardless of existence"
+			echo "                          of trigger / standby files."
+			echo "    Optional, default: N/A"
+			echo "    Description:       Without this flag the script will require"
+			echo "                       presence of trigger file."
+			echo "                       With the flag set the script will create"
+			echo "                       trigger file as needed."
+			echo " "
+			echo "Error Codes:"
+			echo "  1 - Wrong user. The script has to be executed as 'postgres' user."
+			echo "  2 - Argument error. Caused either by bad format of provided flags and"
+			echo "      arguments or if a mandatory argument is missing."
+			echo "  3 - Inapropriate trigger / standby files. See -f flag for details."
+			echo "  4 - Error creating/deleting/copying configuration files"
+			echo "      (postgresql.conf and recovery.conf)."
+			echo "      Hint: ensure that templates exist and check permissions."
+			echo "  5 - Error creating / altering replication_user."
+            exit 0
+            ;;
+
+		-t)
+
+			shift
+
+            if test $# -gt 0; then
+
+                trigger_file=$1
+
+            else
+
+                echo "ERROR: -t flag requires trigger file to be specified."
+                exit 2
+
+            fi
+
+            shift
+            ;;
+
+        --trigger-file=*)
+
+            trigger_file=`echo $1 | sed -e 's/^[^=]*=//g'`
+            shift
+            ;;
+
+		-s)
+
+			shift
+
+            if test $# -gt 0; then
+
+                standby_file=$1
+
+            else
+
+                echo "ERROR: -s flag requires standby file to be specified."
+                exit 2
+
+            fi
+            shift
+            ;;
+
+        --standby-file=*)
+
+            standby_file=`echo $1 | sed -e 's/^[^=]*=//g'`
+
+            shift
+            ;;
+
+		-d)
+
+			shift
+
+            if test $# -gt 0; then
+
+                demote_host=$1
+
+            else
+
+                echo "ERROR: -d flag requires host that will be demoted to be specified."
+                exit 2
+
+            fi
+
+            shift
+            ;;
+        --demote-host=*)
+
+            demote_host=`echo $1 | sed -e 's/^[^=]*=//g'`
+
+            shift
+            ;;
+
+		-u)
+
+			shift
+
+            if test $# -gt 0; then
+
+                replication_user=$1
+
+            else
+
+                echo "ERROR: -u flag requires replication user to be specified."
+                exit 2
+
+            fi
+
+            shift
+            ;;
+        --user=*)
+
+            replication_user=`echo $1 | sed -e 's/^[^=]*=//g'`
+
+            shift
+            ;;
+		-p)
+
+			shift
+
+            if test $# -gt 0; then
+
+                replication_password=$1
+
+            else
+
+                echo "ERROR: -p flag requires replication password to be specified."
+                exit 2
+
+            fi
+
+            shift
+            ;;
+
+        --password=*)
+
+            replication_password=`echo $1 | sed -e 's/^[^=]*=//g'`
+
+            shift
+            ;;
+
+        -f|--force)
+
+            force=true
+            shift
+            ;;
+
+        *)
+
+			echo "ERROR: Unrecognized option $1"
+			exit 2
+            ;;
+
+    esac
+
 done
 
+# Ensuring that 'postgres' runs the script
+if [ "$(id -u)" -ne "$(id -u postgres)" ]; then
+
+    echo "ERROR: The script must be executed as 'postgres' user."
+    exit 1
+
+fi
+
 if [ "$replication_password" = "" ]; then
-        echo "ERROR: --password is mandatory. For help execute 'promote -h'"
-        exit 2
+
+    echo "ERROR: --password is mandatory. For help execute 'promote -h'"
+    exit 2
+
 fi
 
 if $debug; then
+
 	echo "DEBUG: The script will be executed with the following arguments:"
 	echo "DEBUG: --trigger-file=$trigger_file"
 	echo "DEBUG: --standby_file=$standby_file"
 	echo "DEBUG: --demote-host=$demote_host"
 	echo "DEBUG: --user=$replication_user"
 	echo "DEBUG: --password=$replication_password"
+
 	if $force; then
 		echo "DEBUG: --force"
 	fi
+
 fi
 
 echo "INFO: Checking if standby file exists..."
 if [ -e $standby_file ]; then
 
 	if $force; then
+
 		echo "INFO: Standby file found. Deleting..."
 		rm $standby_file
+
 	else
+
 		echo "ERROR: Cannot promote server that contains standby file: ${standby_file}"
 		exit 3
+
 	fi
 	
 fi
@@ -175,11 +243,15 @@ echo "INFO: Checking if trigger file exists..."
 if [ ! -e $trigger_file ]; then
 
 	if $force; then
+
 		echo "INFO: Trigger file not found. Creating a new one..."
 		echo "Promoted at: $(date)" >> $trigger_file
+
 	else
+
 		echo "ERROR: Cannot promote server that does not contain trigger file: ${trigger_file}"
 		exit 3
+
 	fi
 	
 fi
